---
title: "Customer Churn Analytics"
output:
  flexdashboard::flex_dashboard: default
runtime: shiny_prerendered
---

```{r setup}
library(keras)
library(flexdashboard)
library(billboarder)
library(tidyverse)
library(scales)
library(lime)
library(glue)


load('keras_data.RData')
model_keras <- load_model_hdf5('keras_model.hdf5', custom_objects = NULL, compile = FALSE)

#### setup customer scorecard inputs ####
main_vars <- c('tenure', 'Contract', 'InternetService', 'MonthlyCharges', 
               'OnlineBackup', 'OnlineSecurity', 'DeviceProtection', 
               'TechSupport', 'StreamingMovies', 'PhoneService')
commercial_vars <- c('InternetService', 'OnlineBackup', 'OnlineSecurity', 
                     'DeviceProtection', 'TechSupport', 'StreamingMovies', 
                     'PhoneService')
financial_vars <- c('PaymentMethod')
customer_feature_vars <- c(main_vars, commercial_vars, financial_vars) %>% unique

#### transform original dataset ####
churn_data_raw <- read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv") %>% 
  mutate(
    tenure_range = case_when(
        tenure < 12 ~ '< 1 Yr',
        tenure < 24 ~ '1-2 Yrs',
        tenure < 36 ~ '2-3 Yrs',
        tenure >= 36 ~ 'Over 3 Yrs',
        TRUE ~ 'NA'
    ),
    monthly_charge_range = case_when(
        MonthlyCharges < 20 ~ '< 20 per Month',
        MonthlyCharges < 50 ~ '20-50 per Month',
        MonthlyCharges < 100 ~ '50-100 per Month',
        MonthlyCharges >= 100 ~ 'Over 100 per Month',
        TRUE ~ 'NA'
    )
  )

churn_data_tbl <- churn_data_raw %>%
  drop_na() %>%
  select(Churn, everything())


# Setup lime::model_type() function for keras
model_type.keras.models.Sequential <- function(x, ...) {
    return("classification")
}

# Setup lime::predict_model() function for keras
predict_model.keras.models.Sequential <- function(x, newdata, type, ...) {
    pred <- predict_proba(object = x, x = as.matrix(newdata))
    return(data.frame(Yes = pred, No = 1 - pred))
}
```


Customer Scorecard {data-orientation=rows}
===========================================================================

Sidebar {.sidebar}
----------------------------

#### Customer ID

```{r}
selectInput('customer_id', NULL, unique(test_tbl_with_ids$customerID))
```

#### Churn Risk

```{r}
gaugeOutput("churn_risk", width = "220px")
```

```{r, context="server"}
output$churn_risk <- renderGauge({
  
  req(input$customer_id)
        
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  test_tbl_with_ids_predictions <- test_tbl_with_ids %>% 
    mutate(churn_prob = predictions$Yes)
  
  customer_tbl <- test_tbl_with_ids_predictions %>% 
    filter(customerID == selected_customer_id)
        
  gauge(round(customer_tbl$churn_prob * 100, digits = 1), 
        min = 0, 
        max = 100,
        gaugeSectors(
          success = c(0,33),
          warning = c(33, 66),
          danger = c(67,100)
        ),
        symbol = "%")
})
```


Row
----------------------------

```{css}
.value-box .value-output,
.value-box .caption {
  font-size: 24px;
}
```

### Main Strategy

```{r}
valueBoxOutput("main_strategy")
```

```{r, context="server"}
output$main_strategy <- renderValueBox({
  
   req(input$customer_id)
        
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  customer_tbl <- test_tbl_with_ids %>% 
      filter(customerID == selected_customer_id)
  
  if (customer_tbl$tenure <= 9) {
      main_strategy <- 'Retain until one year'
  } else if (customer_tbl$tenure > 9 | customer_tbl$Contract == 'Month-to-month') {
      main_strategy <- 'Upsell to annual contract'
  } else if (customer_tbl$tenure > 12 & customer_tbl$InternetService == 'No') {
      main_strategy <- 'Offer internet service'
  } else if (customer_tbl$tenure > 18 & customer_tbl$MonthlyCharges > 50) {
      main_strategy <- 'Offer discount in monthly rate'
  } else if (customer_tbl$tenure > 12 & 
             customer_tbl$Contract != 'Month-to-month' & 
             ((customer_tbl$OnlineBackup == 'No' & 
               customer_tbl$OnlineSecurity == 'No' & 
               customer_tbl$DeviceProtection == 'No' & 
               customer_tbl$TechSupport == 'No' & 
               customer_tbl$StreamingMovies == 'No') 
              | customer_tbl$PhoneService == 'No')) {
      main_strategy <- 'Offer additional services'
  } else {
      main_strategy <- 'Retain and maintain'
  }
  valueBox("Main Strategy", caption = main_strategy, color = "info")
})
```

### Commercial Strategy

```{r}
valueBoxOutput("commercial_strategy")
```

```{r, context="server"}
output$commercial_strategy <- renderValueBox({
  
  req(input$customer_id)
        
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  customer_tbl <- test_tbl_with_ids %>% 
      filter(customerID == selected_customer_id)
  
  if ((customer_tbl$InternetService == 'DSL' & 
       customer_tbl$OnlineBackup == 'No' & 
       customer_tbl$OnlineSecurity == 'No' & 
       customer_tbl$DeviceProtection == 'No' & 
       customer_tbl$TechSupport == 'No' & 
       customer_tbl$StreamingMovies == 'No') 
      | customer_tbl$PhoneService == 'No') {
      commercial_strategy <- 'Offer additional services'
  } else if (customer_tbl$InternetService == 'Fiber optic') {
      commercial_strategy <- 'Offer tech support and services'
  } else if (customer_tbl$InternetService == 'No') {
      commercial_strategy <- 'Upsell to internet service'
  } else {
      commercial_strategy <- 'Retain and maintain'
  }
  
  valueBox("Commercial Strategy", caption = commercial_strategy, color = "primary")
})
```

### Financial Strategy

```{r}
valueBoxOutput("financial_strategy")
```

```{r, context="server"}
output$financial_strategy <- renderValueBox({
  
  req(input$customer_id)
        
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  customer_tbl <- test_tbl_with_ids %>% 
      filter(customerID == selected_customer_id)
  
  if (customer_tbl$PaymentMethod %in% c('Mailed Check', 'Electronic Check')) {
    financial_strategy <- 'Move to credit card or bank transfer'
  } else {
    financial_strategy <- 'Retain and maintain'
  }
  
  valueBox("Financial Strategy", caption = financial_strategy, color = "warning")
})
```


Row
----------------------------

### Customer Details {data-width=33}

```{css}
.dataTables_wrapper table thead{
  display:none;
}
```

```{r}
DT::dataTableOutput('customer_info_tbl')
```

```{r, context="server"}
output$customer_info_tbl <- DT::renderDataTable({
        
  req(input$customer_id)
  
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  customer_info <- test_tbl_with_ids %>% 
      filter(customerID == selected_customer_id) %>% 
      mutate(tenure = paste0(tenure, ifelse(tenure == 1, ' Month', ' Months'))) %>% 
      select(customer_feature_vars) %>% 
      gather(metric, value)
  
  DT::datatable(
    customer_info, 
    rownames = NULL, 
    options = list(
        dom = 't', 
        bSort = FALSE, 
        paging = FALSE
    )
  )
})
```

### Contributions to Churn (LIME) {data-width=67}

```{r}
billboarderOutput('customer_explanation')
```

```{r, context="server"}
output$customer_explanation <- renderBillboarder({
     
  req(input$customer_id)
  
  selected_customer_id <- test_tbl_with_ids$customerID[1]
  selected_customer_id <- input$customer_id
  
  # Run lime() on training set
  explainer <- lime(
      x = x_train_tbl,
      model = model_keras,
      bin_continuous = FALSE)
  
  customer_index <- test_tbl_with_ids %>% 
      mutate(rownum = row_number()) %>% 
      filter(customerID == selected_customer_id) %>%
      select(rownum)
  
  # Run explain() on explainer
  set.seed(42)
  explanation <- explain(
      x_test_tbl[customer_index$rownum,], 
      explainer = explainer, 
      n_labels = 1, 
      n_features = length(x_test_tbl),
      kernel_width = 0.5)
  
  type_pal <- c('Supports', 'Contradicts')
  explanation$type <- factor(ifelse(sign(explanation$feature_weight) == 
                                        1, type_pal[1], type_pal[2]), levels = type_pal)
  description <- paste0(explanation$case, "_", explanation$label)
  desc_width <- max(nchar(description)) + 1
  description <- paste0(format(description, width = desc_width), 
                        explanation$feature_desc)
  explanation$description <- factor(description, levels = description[order(abs(explanation$feature_weight))])
  explanation$case <- factor(explanation$case, unique(explanation$case))
  
  explanation_plot_df <- explanation %>%
      mutate(churn_predictor = case_when(
          (label == 'Yes' & type == 'Supports') | (label == 'No' & type == 'Contradicts') ~ 'More likely to churn',
          (label == 'Yes' & type == 'Contradicts') | (label == 'No' & type == 'Supports') ~ 'Less likely to churn'
      )) %>%
      arrange(-abs(feature_weight)) %>% 
      head(20)
  
  billboarder() %>%
      bb_barchart(
          data = explanation_plot_df,
          mapping = bbaes(x = feature_desc, y = feature_weight, group = churn_predictor),
          rotated = TRUE,
          stacked = TRUE
      ) %>%
      bb_colors_manual('Less likely to churn' = 'rgba(63, 182, 24, 0.7)', 'More likely to churn' = 'rgba(255, 0, 57, 0.7)')
  
})
```

Churn Analysis
===========================================================================

